name: CI/CD for ToDo List

on:
  push:
    branches: ['main']
  pull_request:
    branches: ['main']

jobs:
  build-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install Docker Compose
        run: sudo apt-get update && sudo apt-get install -y docker-compose

      - name: Build and Start all services
        run: docker-compose up -d --build

      - name: Wait until backend is healthy
        run: |
          echo "⏳ Waiting for backend..."
          for i in {1..30}; do
            if curl -s http://localhost:3001/api/tasks > /dev/null; then
              echo "✅ Backend is ready"
              exit 0
            fi
            echo "⏳ Waiting for backend ($i/30)..."
            sleep 5
          done
          echo "❌ Backend did not become ready in time"
          docker-compose logs
          exit 1

      - name: Test frontend
        run: curl -f http://localhost:3000 || exit 1

      - name: Shutdown
        run: docker-compose down --volumes --remove-orphans
